### PR TITLE
Lingual stubs and label field by default 

### PR DESCRIPTION
**Pull request by Mello21century**
A small change in stub to allow multilingual if used and label field for each field by default

### CODE REVIEW

**Comment by promatik** [comment]
In generally I agree with this changes, I **always** do this after generating a CRUD.
But since we are going to allow the publish and customization of the stubs, I'm not 100% sure if we should merge this.

@tabacitu what do you think?

**Comment by pxpm** [comment]
@promatik I think the publishable stubs should have this by default, so I would merge this and make the stubs publishable. My reasoning is that more people would be publishing the stubs to have the label translated than people publishing them to don't translate the label. 

Let me know,
Pedro

**Comment by tabacitu** [comment]
Thanks for submitting this @Mello21century ! I'm not sure we _should_ do this, though. Personally I never do this - since most of my projects are single-language, and that language is English... But I do see how this can be very useful for multi-language projects, and even single-language-non-English projects... How it would avoid some manual coding.

But the fact that single-language projects don't need this makes me think that... we probably should't do this _by default_. No reason to bloat up the files for _those who don't need translations_... to help _those who do need them_. Wouldn't you agree? Am I missing something here?

I do agree that a lot of people might want this, though. So I definitely want a solution for those people. But I don't think we should force single-language project to use translations strings, when they don't actually need it. 

Looking at it from that perspective, perhaps the best solution would be customizable stubs. Which we do want to offer, in [DevTools](https://backpackforlaravel.com/products/devtools), in the not-too-distant future. Basically to have a custom stub in your Backpack account, and any time you use DevTools to generate stuff, it'll use your custom stubs instead of the default ones.

Personally I wouldn't merge this, I'd say let's hold out for DevTools to provide customizable stubs. That's because:
- We don't have a %, to know how many devs use translation strings and how many don't so... pushing a slightly worse UX for some users, in order to slightly improve the UX for other users... not something I think we should do 🤷‍♂️
- Even if we do decide to add translatable strings by default, who says devs want to store it in the general translation file? Maybe they want it stored into `admin`, so it would need that prefix. Maybe in a different file... 🤷‍♂️

Let me know what you guys think, if I'm missing something.
Cheers!

**Comment by tabacitu** [comment]
Yup, thought about it again... still don't agree to do this, sorry @Mello21century . It's not fair to force single-language projects to use multi-language features.

Please don't let this stop you from opening other issues or PRs. We core dev have A BUNCH of PRs that never got merged either - it's the way it is. What one day seems like a great idea might turn out to be not so great. I've had hundreds of those myself 😀

That being said, I make mistakes all the time. So if you think my judgement was off on this one please feel free to reply and convince me otherwise. I'm open.

Cheers!

**Pull request closed without merging**
