### PR TITLE
Fixes #13 - Allows you to publish buttons/fields/columns

### LINKED ISSUE #13: [Feature] Publish field/button/column command
Copied from https://github.com/Laravel-Backpack/CRUD/issues/171

If overwriting fields/buttons/columns happens a lot, it would help if we had a command to take the standard blade file and place it in the correct directory, like /resources/views/vendor/backpack/crud/fields.

The command could look something like:

```php
php artisan backpack:overwrite-field --name=select2
php artisan backpack:overwrite-column --name=date
php artisan backpack:overwrite-button --name=preview
```

But again - this might not be an actual issue. Do people actually overwrite fields/columns/buttons a lot?

### PR DESCRIPTION
**Pull request by OwenMelbz**
Copies a version of the package view into your local resources folder for modification

# Usage e.g

```sh
php artisan backpack:overwrite field select2
php artisan backpack:overwrite field array

php artisan backpack:overwrite button create
php artisan backpack:overwrite button edit

php artisan backpack:overwrite column boolean
php artisan backpack:overwrite column image
```

### CODE REVIEW

**Comment by AbbyJanke** [comment]
@tabacitu has been sitting here for awhile, and thoughts on this or is it stale/not wanted? Just looking to clean up PRs/Issues been sitting around for awhile.

**Comment by tabacitu** [comment]
@AbbyJanke thank you for that. And @OwenMelbz thank you for the PR.

**I still think this is a good idea**, just haven't had the time to properly test & polish this PR. I think it would be very useful to all of us. The only thing it's missing from what I can tell is the ability to also overwrite "filters".

**Comment by OwenMelbz** [comment]
Ha a lot happened in a year. Deffo still want this, but ideally maybe closer to the core :p

But should be rewritten to be more dynamic now, maybe automatically create a list of available fields to publish, and take less strings to allow for less errors

**Comment by tabacitu** [comment]
@OwenMelbz totally agree this is no longer the place for it. I've copy pasted your code into CRUD and added the Filters functionality. I think it works GREAT as-is. Sure, we can improve it in time, but that might take another year and a half :-) So I say let's launch it like this: https://github.com/Laravel-Backpack/CRUD/commit/0e7f69b013f942379354417cd59b86489c6dc38b

Thanks again. Cheers!

**Pull request closed without merging**
