### PR TITLE
Models should have a `HasFactory` trait

### PR DESCRIPTION
**Pull request by egyjs**
Models included the `HasFactory` trait in version >= 8 of Laravel

### CODE REVIEW

**Review by promatik — APPROVED** [review]
Hi @egyjs, thank you once again!

I think we haven't added the `HasFactory` trait because [DevTools](https://backpackforlaravel.com/products/devtools) does it with one click 😅

But anyway, since artisan command `make:model` already provides the `HasFactory`, maybe we should add it too.

I aprove this as is, I'll let @tabacitu decide on that.

**Comment by pxpm** [comment]
This would be a BC for people using <L8

I think we can only introduce this by creating two different stubs, one for L6,7 and another for L8 and calling the correct stub here: 
https://github.com/Laravel-Backpack/Generators/blob/0c72a89063c75ce68a32726558b6b19cd60a8f4f/src/Console/Commands/ModelBackpackCommand.php#L43

It might be 4 stubs in total because of `soft-deletes` too. 

Thanks for the contribution @egyjs ! Let me know if you want to do the needed changes or me or @promatik can do it later.

Best,
Pedro

**Comment by egyjs** [comment]
> It might be 4 stubs in total because of soft-deletes too.

I don't think it's the best method to create a lot of stubs for small differences, but I'm pondering a better approach.

**Comment by tabacitu** [comment]
Hmm interesting... I think it's a bit overkill to have both stubs in one version... Complicates the code for a time, without adding too much benefit. At the end of the day, the generated model is supposed to work with Backpack, not with a Factory that we haven't generated... On the other hand, if that's how Laravel generates the models... we should probably do it.

I'd rather wait to launch Backpack 4.2, where we'll drop support for Laravel <8. Then we can merge this PR as-is.

Thank you @egyjs ! 🙏

**Comment by egyjs** [comment]
I was thinking of creating method that add the "use trait" 
For example
```php
If(app()->version() = "8") addTrait("Trait Name","TraitNameSpace")
```
Instead of creating many stubs

**Comment by egyjs** [comment]
@tabacitu 
As I mentioned earlier, instead of creating so many stubs, or so, we can just make it dynamic

here is a method made by me so you can add any trait to any class or stubs.
```php
    /**
     * Add Trait to Class(Model).
     *
     * @param $namespaceModels
     * @param $traitNamespace
     * @return boolean|int
     *
     */
    protected function addTrait($namespaceModels,$traitNamespace){
        $traitName = class_basename($traitNamespace);

        $modelStr =  file_get_contents($this->getPath($namespaceModels));
        $regex = '/(class.(\S+).(extends).(\S+)(.+?)(\n?)({))/m';
        $replaceWith = "use $traitNamespace; \n\n$1\n    use $traitName;";

        $modelAfterTraitAdded = preg_replace($regex, $replaceWith, $modelStr);

        return file_put_contents($this->getPath($namespaceModels), $modelAfterTraitAdded);
    }
```

**Comment by tabacitu** [comment]
Heads-up guys. I think we should now merge this, if we release a version that only supports Laravel 5. Which... we should do anyway. As I said in https://github.com/Laravel-Backpack/demo/pull/204, I don't see any harm in having the HasFactory trait on the model, _even if_ there is no factory.

Let's do this in Backpack 5.x 💪 🎉

**Pull request merged**
