### PR TITLE
Update crud-controller.stub

### PR DESCRIPTION
**Pull request by tholu**
Use double backslash in setModel (single backslash is used for escaping).

### CODE REVIEW

**Comment by OwenMelbz** [comment]
Hi,

Out of interest what does this actually achieve? I understand that your escaping them, but why do you think it's needed to be done?

**Comment by tholu** [comment]
@OwenMelbz Backslashes in double quotes need to be escaped in PHP. You should always escape backslashes, even in single quotes. If you use the generator with a model called e.g. `nastybug` (or anything starting with an n), the code looks like that:

`$this->crud->setModel("App\Models\nastybug")`

This is a problem, because now the backslash matches the linebreak `\n`, see here: https://3v4l.org/orlpa

Double backslashes avoid that problem: https://3v4l.org/Qre5Q

**Comment by tholu** [comment]
I guess the proper use of backslashes should also be updated throughout the documentation and other places where currently only single backslashes are used (e.g. found here: https://laravel-backpack.readme.io/docs/crud-example).

**Comment by tholu** [comment]
The other (perhaps prettier, because it avoids a lot of double backslashes) option would be to use single quotes, e.g.

`$this->crud->setModel('App\Models\nastybug')`

This only fails if the backslash is at the end of the string, so that the closing single quote is escaped.

**Comment by aaranmcguire** [comment]
Just noticed this PR. Just created one to change these methods to use single quotes. #22.

**Comment by pavoltanuska** [comment]
Why not omit the slashes altogether here and import the class at the top with `use` and use the `::class` notation?

**Comment by tabacitu** [comment]
Hi guys,

Thanks a lot for the collaboration here. I agree there was a problem, but it's since been fixed using @pavoltanuska 's PR #22 - single quotes instead of double quotes. I think is this is the prettier solution.

Thank you @tholu for spotting the bug and submitting the PR, and everybody else for pitching in. Team Backpack!! :-)

Cheers!

**Pull request closed without merging**
