### PR TITLE
added quotes to $kebabName variable

### PR DESCRIPTION
**Pull request by iMokhles**
mistyped it previously my bad :(

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks for the PR @iMokhles - but I don't understand why this is needed - could you please explain? In my tests the route is generated just fine without the double quotes.

**Comment by tabacitu** [comment]
Ah ok is it the same as https://github.com/Laravel-Backpack/Generators/pull/81 :smile: ?

**Comment by MarioVillani** [comment]
not all checks passed, please check it!

   ParseError 

  syntax error, unexpected '$kebabName' (T_VARIABLE), expecting ']'

  at vendor/backpack/generators/src/Console/Commands/ChartBackpackCommand.php:41

**Comment by tabacitu** [comment]
Indeed - thanks a lot @MarioVillani & @KoenJanssensPD , it was my bad for merging without TravisCI's approval. I even received an email about it, but Travis cried wolf so many times, and the PR was so small, that I figured it's probably nothing. I was wrong, obviously - I'm very sorry for the frustration and confusion this must have caused you guys. 

It's now fixed through #92 . Anybody doing `composer install --dev backpack/generators` right now should be able to get 3.1.3 which has this fixed. If not (because of caching), `composer install --dev backpack/generators:"^3.1.3"` should definitely get that version.

Sorry again for the trouble. I promise I'll make it up to you with a cool new package - a UI for these generators - `backpack/devtools`. It will help you forget _all about_ the generator commands - you won't need to remember a thing to generate backpack stuff (or even plain old Eloquent models), you'd be able to do it from the user interface. I estimate it'll save us all hours, for every project. Here's a sneak peek of the MVP:
Screenshot 2020-06-22 at 23 46 25

**Pull request merged**
